apiVersion: batch/v1
kind: Job
metadata:
  name: tts-job
  labels:
    app.kubernetes.io/name: tts-job
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tts-job
    spec:
      serviceAccountName: tts-account
      restartPolicy: Never
      containers:
        - name: tts
          imagePullPolicy: Always
          image: dodasts/tts-cache:v0.1.1-k8s
          args:
            - --cache-certs
          volumeMounts:
            - name: config
              mountPath: "/app"
          resources:
            limits:
              memory: "500M"
              cpu: "100m"
            requests:
              memory: "100M"
              cpu: "100m"
      volumes:
        - name: config
          configMap:
            name: ttsconfig
